GET  http://localhost:8080/games

###
GET http://localhost:8080/games/1

###
POST http://localhost:8080/games
Content-Type: application/json

{
    "name": "Joao Maia",
    "genre": "Qualquer dois",
    "price": 59.12,
    "releaseDate": "2026-10-20"
}